Arduino
EPostanogova/BlackWigwam_SmartBot pull request #21
Opened 2021-04-29 14:01 UTC by EPostanogova

2021-04-29 15:01 UTC, serykhelena requested changes

2021-04-29 15:01 UTC, serykhelena commented on arduino/utils.ino/utils.ino.ino
> + Serial.print(msg);
7-8 должны быть в отдельной функции echo()

2021-04-29 15:01 UTC, serykhelena commented on arduino/utils.ino/utils.ino.ino
> +String msg=Serial.readString();
добавить проверку Serial.available()

2021-04-29 15:01 UTC, serykhelena commented on src/arduino.py
> +        self.com_port="COM6"
self.com_port = com_port, а не константа. Иначе смысла нет в аргументах в конструкторе

2021-04-29 15:01 UTC, serykhelena commented on src/arduino.py
> +        self.baudrate=115200
аналогично, как и com_port

2021-04-29 15:01 UTC, serykhelena commented on src/arduino.py
> +        self.ser = serial.Serial(com_port,baudrate)
добавь timeout=5 s

2021-04-29 15:01 UTC, serykhelena commented on src/arduino.py
> +    def echo(self,msg=input("Введите что-нибудь: ")):
input из аргумента лучше убрать, давай лучше задавать статическую строку. А не через консоль

2021-04-29 15:01 UTC, serykhelena commented on src/arduino.py
> +        print (ser.readline())
не надо print, давай сохранишь в отдельную переменную. и вернёшь её из функции

2021-04-29 15:01 UTC, serykhelena commented on src/arduino.py
> +
ещё создай отдельный файл (можно внутри папки src) test_arduino.py В котором создаёшь объект ArduinoConnector с нужными конфигами. И дёргаешь echo("Hello") и print полученное значение из echo

2021-05-03 19:50 UTC, serykhelena requested changes

2021-05-03 19:50 UTC, serykhelena commented on src/arduino.py
> +        time.sleep(5)
не, я про то, что в serial.Serial есть ещё аргумент timeout, который можно задать 5 секунд - на всякий пожарный. Т.к. ардуина довольно долго думает временами. А строчка 12 не нужна (=

2021-05-03 19:50 UTC, serykhelena commented on src/arduino.py
> +        self.ser.write(msg)
чтобы тебе не приходилось через bytes кодировать  сообщение, можно сразу отправить в правильной кодировке. Т.е. можно сделать self.ser.write(str.encode(msg)). Тогда на вход метода можно подавать сообщение в виде обчной строки, а внутри уже кодировать

2021-05-03 19:50 UTC, serykhelena commented on src/arduino.py
> +        self.ser.close()
А где return msg_echo из метода?

2021-05-03 19:50 UTC, serykhelena commented on src/test_arduino.py
> +AC.echo(msg=rez)
когда добавить retunt в методе echo, то можно будет присвоить результат переменной и её уже вывести в print. Сейчас по идее на 7 строчке должна быть ошибка, т.к. переменная msg_echo не определена

2021-05-04 19:37 UTC, serykhelena requested changes

2021-05-04 19:37 UTC, serykhelena commented on arduino/utils.ino/utils.ino.ino
> +  Serial.write("Hello");
попробуй здесь использовать функцию print. Чтобы использовать write, тебе нужно использовать цикл 
for(int i = 0; i < msg.length(); i++)
{
     Serial.write(msg[i]);  
}

Что-то типа такого

2021-05-04 19:44 UTC, EPostanogova commented on arduino/utils.ino/utils.ino.ino
> +  Serial.write("Hello");
Попробовала и так и так. Функция возвращает b' '

2021-05-04 19:48 UTC, serykhelena commented on arduino/utils.ino/utils.ino.ino
> +  Serial.write("Hello");
А ты это в консоли видишь, запуская скрипт питона?

2021-05-04 19:52 UTC, serykhelena commented on arduino/utils.ino/utils.ino.ino
> +  Serial.write("Hello");
Попробуй убрать 11 строчку совсем

2021-05-04 19:54 UTC, serykhelena commented on src/arduino.py
> +        msg_echo=self.ser.readline()
Ещё можешь попробовать здесь вместо readline использовать self.ser.read(self.ser.inWaiting())

2021-05-04 20:10 UTC, EPostanogova commented on arduino/utils.ino/utils.ino.ino
> +  Serial.write("Hello");
Да, это в консоли. Я не знаю только, в мониторе порта что-то должно отображаться? Сейчас там пусто. 11 строчку убрала

2021-05-04 20:24 UTC, serykhelena commented on arduino/utils.ino/utils.ino.ino
> +  Serial.write("Hello");
да, всё верно. Нужно смотреть в консоли. Монитор порта по идее не должен работать, т.к. этот порт должен питон захватывать

2021-05-04 20:33 UTC, EPostanogova commented on src/arduino.py
> +        msg_echo=self.ser.readline()
попробовала, все также

2021-05-04 20:34 UTC, serykhelena commented on src/arduino.py
> +        msg_echo=self.ser.readline()
залей код, пожалуйста (=

2021-05-04 20:50 UTC, serykhelena commented on arduino/utils.ino/utils.ino.ino
> +  Serial.print(msg);
А если не запускать питон скрипт, а из монитора порта отправить строку, то выводит всё правильно?

2021-05-04 21:17 UTC, EPostanogova commented on arduino/utils.ino/utils.ino.ino
> +  Serial.print(msg);
Да, все правильно выводит.

2021-05-05 06:53 UTC, serykhelena commented on src/arduino.py
> +
Попробуй сюда добавить строку self.ser.flush()

2021-05-05 07:35 UTC, serykhelena commented on arduino/utils.ino/utils.ino.ino
> +  Serial.print(msg);
Тогда может быть дело в питоне или в функции print

2021-05-05 11:07 UTC, EPostanogova commented on src/arduino.py
> +
Ничего не изментлось. Буду еще читать про эту проблему.

2021-05-09 07:30 UTC, serykhelena commented on src/arduino.py
> +    def echo(self,msg):
Проблема была в том, что задержки в 1 секунду - не хватает ардуино, она и  не успевает принять данные и отправить. Поэтому если увеличить задержку, то всё заработает. Но я тут подумала, что если мы будет увеличивать задержку, то это как-то не очень изящно. А просто в while ждать, когда ардуина созреет рисковано, т.к. если ардуина зависнет, питон тоже зависнет. Поэтому предлагаю добавить что-то типа timeout в функцию 

self.ser.write(str.encode(msg))
msg_echo = ""
start_time = datetime.datetime.now()
 while len(msg_echo) == 0:
       msg_echo = self.ser.read(self.ser.inWaiting())
       cur_time = datetime.datetime.now()
       if (cur_time - start_time).total_seconds() >= timeout * 60:
           break
self.ser.close()
return  msg_echo.decode("utf-8")

Не забудь подключить библиотеку datetime 

в return я добавила decode, чтобы получать не байт-строку, а просто строку

2021-05-12 13:51 UTC, serykhelena requested changes

2021-05-12 13:51 UTC, serykhelena commented on src/arduino.py
> +        timeout=3
timeout лучше вынести в аргументы и сделать дефолтное значение 3

2021-05-12 13:51 UTC, serykhelena commented on src/test_arduino.py
> +AC=ArduinoConnector(com_port='COM6',baudrate=115200)
оберни этот код в `if __name__ == "__main__":`

2021-05-12 13:52 UTC, serykhelena commented
В результате заработало, ты проверила?

2021-05-12 16:40 UTC, EPostanogova reviewed
> В результате заработало, ты проверила?

Нет. Обернула в if __name__ == "__main__":, пробовала увеличить задержку, все по прежнему. Порт меняла тоже.

2021-05-12 16:40 UTC, EPostanogova commented on src/arduino.py
> +    def echo(self,msg):
Не очень поняла, где задавать аргумент timeout, в аргументах функции?

2021-05-12 16:40 UTC, EPostanogova commented on src/arduino.py
> +    def echo(self,msg):
Прото я сейчас попробовала и в старом коде задержку увеличить и потом сделала, как ты выше написала, но у меня вообще ничего не выводит) Я вот думаю, что не поняла все таки как и где timeout задается

2021-05-15 13:11 UTC, serykhelena approved these changes

2021-05-15 13:11 UTC, merged